# app çš„å”¯ä¸€ id,ä¸Šæž¶åˆ°å•†åº—éœ€è¦ä¿è¯ä¸è¦å†²çª,å°½é‡ä½¿ç”¨å¼€å‘è€…è‡ªå·±çš„åŸŸåä½œä¸ºåŽç¼€.
package: cloud.lazycat.app.liu.strapi
# app çš„ç‰ˆæœ¬
version: 5.25.0

name: Strapi
keyword: strapi,cms,headless
description: Strapi æ˜¯ä¸€ä¸ªå¼€æºçš„æ— å¤´å†…å®¹ç®¡ç†ç³»ç»Ÿ (Headless CMS)

# è½¯ä»¶åç§°,ä¼šæ˜¾ç¤ºåœ¨å¯åŠ¨å™¨ä¹‹ç±»çš„åœ°æ–¹
locales:
  zh:
    name: Strapi CMS
    description: |
      ## Strapi - å¼€æºæ— å¤´å†…å®¹ç®¡ç†ç³»ç»Ÿ

      Strapi å®˜æ–¹ç½‘ç«™ï¼šhttps://strapi.io/

      Strapi æ˜¯ä¸€ä¸ªé¢†å…ˆçš„å¼€æºæ— å¤´å†…å®¹ç®¡ç†ç³»ç»Ÿï¼ˆHeadless CMSï¼‰ï¼Œå®ƒå®Œå…¨åŸºäºŽ JavaScript/TypeScript æž„å»ºï¼Œä¸ºå¼€å‘è€…æä¾›äº†çµæ´»çš„ API ä¼˜å…ˆçš„å†…å®¹ç®¡ç†è§£å†³æ–¹æ¡ˆã€‚

      ## ä¸»è¦åŠŸèƒ½

      - ðŸš€ å¿«é€Ÿæž„å»º RESTful API å’Œ GraphQL API
      - ðŸ“ å¯è§†åŒ–å†…å®¹ç±»åž‹æž„å»ºå™¨ï¼Œæ— éœ€ç¼–ç å³å¯åˆ›å»ºæ•°æ®æ¨¡åž‹
      - ðŸŽ¨ ç›´è§‚çš„ç®¡ç†é¢æ¿ï¼Œæ–¹ä¾¿å†…å®¹ç¼–è¾‘å’Œç®¡ç†
      - ðŸ” å†…ç½®ç”¨æˆ·æƒé™å’Œè§’è‰²ç®¡ç†ç³»ç»Ÿ
      - ðŸ”Œ ä¸°å¯Œçš„æ’ä»¶ç”Ÿæ€ç³»ç»Ÿï¼Œå¯æ‰©å±•åŠŸèƒ½
      - ðŸ“± æ”¯æŒå¤šè¯­è¨€å†…å®¹ç®¡ç†
      - ðŸ–¼ï¸ åª’ä½“åº“ç®¡ç†ï¼Œæ”¯æŒå›¾ç‰‡ã€è§†é¢‘ç­‰å¤šç§æ–‡ä»¶ç±»åž‹
      - ðŸŒ æ”¯æŒè‡ªå®šä¹‰å­—æ®µå’Œå…³è”å…³ç³»
      - ðŸ”„ æ”¯æŒ Webhook å’Œè‡ªåŠ¨åŒ–å·¥ä½œæµ
      - ðŸ’» åŸºäºŽ Node.jsï¼Œæ”¯æŒè‡ªæ‰˜ç®¡éƒ¨ç½²

      ## ä½¿ç”¨åœºæ™¯

      - ç½‘ç«™å’Œåº”ç”¨ç¨‹åºçš„åŽç«¯ API å¼€å‘
      - ç§»åŠ¨åº”ç”¨çš„å†…å®¹ç®¡ç†åŽå°
      - ç”µå•†å¹³å°çš„äº§å“ç®¡ç†ç³»ç»Ÿ
      - åšå®¢å’Œæ–‡æ¡£ç½‘ç«™çš„å†…å®¹ç®¡ç†
      - å¤šç«¯å†…å®¹åˆ†å‘å¹³å°

      ## ä½¿ç”¨æ–¹æ³•

      1. å¯åŠ¨åº”ç”¨åŽï¼Œè®¿é—®ç®¡ç†é¢æ¿
      2. é¦–æ¬¡ä½¿ç”¨éœ€è¦åˆ›å»ºç®¡ç†å‘˜è´¦å·
      3. ä½¿ç”¨å†…å®¹ç±»åž‹æž„å»ºå™¨åˆ›å»ºæ•°æ®æ¨¡åž‹
      4. åœ¨å†…å®¹ç®¡ç†å™¨ä¸­æ·»åŠ å’Œç¼–è¾‘å†…å®¹
      5. é€šè¿‡ API è®¿é—®å’Œä½¿ç”¨å†…å®¹æ•°æ®

      ## æŠ€æœ¯æ ˆ

      - åŽç«¯æ¡†æž¶ï¼šKoa.js
      - æ•°æ®åº“ï¼šPostgreSQL
      - å‰ç«¯ï¼šReact
      - å¼€å‘è¯­è¨€ï¼šJavaScript/TypeScript

  en:
    name: Strapi CMS
    description: |
      ## Strapi - Open Source Headless CMS

      Strapi official website: https://strapi.io/

      Strapi is a leading open-source headless content management system (CMS), built entirely on JavaScript/TypeScript, providing developers with a flexible API-first content management solution.

      ## Main Features

      - ðŸš€ Quickly build RESTful APIs and GraphQL APIs
      - ðŸ“ Visual content type builder, create data models without coding
      - ðŸŽ¨ Intuitive admin panel for easy content editing and management
      - ðŸ” Built-in user permissions and role management system
      - ðŸ”Œ Rich plugin ecosystem for extended functionality
      - ðŸ“± Multi-language content management support
      - ðŸ–¼ï¸ Media library management, supporting images, videos and more
      - ðŸŒ Support for custom fields and relationships
      - ðŸ”„ Webhook and automation workflow support
      - ðŸ’» Built on Node.js, supports self-hosted deployment

      ## Use Cases

      - Backend API development for websites and applications
      - Content management backend for mobile apps
      - Product management system for e-commerce platforms
      - Content management for blogs and documentation sites
      - Multi-platform content distribution

      ## How to Use

      1. After launching the app, access the admin panel
      2. First-time use requires creating an admin account
      3. Use the content type builder to create data models
      4. Add and edit content in the content manager
      5. Access and use content data through the API

      ## Tech Stack

      - Backend Framework: Koa.js
      - Database: PostgreSQL
      - Frontend: React
      - Programming Language: JavaScript/TypeScript

# è½¯ä»¶æœ¬èº«çš„ license
license: https://github.com/strapi/strapi/blob/main/LICENSE

# è½¯ä»¶çš„ä¸»é¡µ,ä¼šåœ¨å•†åº—ç­‰åœ°æ–¹ä½“çŽ°
homepage: https://github.com/strapi/strapi

# lpk çš„ä½œè€…,ä¼šåœ¨å•†åº—ç­‰åœ°æ–¹ä½“çŽ°
author: liu

# application ä½œä¸ºä¸€ä¸ªç‰¹æ®Šçš„ container è¿è¡Œï¼Œå¯¹åº”çš„ service åç§°ä¸ºå›ºå®šçš„`app`ï¼Œ å…¶ä»– service å¯ä»¥é€šè¿‡æ­¤åç§°ä¸Ž app è¿›è¡Œé€šè®¯
application:
  #æ˜¯å¦å­˜åœ¨åŽå°ä»»åŠ¡ï¼Œ è‹¥å­˜åœ¨åˆ™ç³»ç»Ÿä¸ä¼šå¯¹æ­¤ app è¿›è¡Œä¸»åŠ¨ä¼‘çœ ç­‰æ“ä½œ
  background_task: true

  # æœŸæœ›çš„ app åŸŸåï¼Œå¦‚æžœç³»ç»Ÿä¸­å·²ç»æœ‰å¯¹åº”åŸŸååˆ™ä¼šæç¤ºç”¨æˆ·é€‰æ‹©å…¶ä»–åŸŸåã€‚ æœ€ç»ˆ app åˆ†é…åˆ°çš„åŸŸåä»¥/lzcapp/run/app.subdomain ä¸ºå‡†
  subdomain: strapi

  routes:
    - /=http://strapi:1337/

  depends_on:
    - strapi

  # æ˜¯å¦å¯ç”¨å¤šå®žä¾‹
  multi_instance: false

services:
  strapi:
    image: ##IMAGE_PLACEHOLDER##
    # image: docker-registry-ui.${LAZYCAT_BOX_NAME}.heiyu.space/strapi:latest
    setup_script: |
      set -e  # Exit immediately if a command exits with a non-zero status
      set -u  # Treat unset variables as an error

      CURRENT_VERSION="5.25.0"
      VERSION_FILE="/backups/.strapi_version"

      # Read installed version
      INSTALLED_VERSION=""
      if [ -f "$VERSION_FILE" ]; then
        INSTALLED_VERSION=$(cat "$VERSION_FILE")
        echo "Installed version: $INSTALLED_VERSION"
      fi

      # Detect if this is a new installation or upgrade
      IS_UPGRADE=false
      if [ -n "$INSTALLED_VERSION" ] && [ "$INSTALLED_VERSION" != "$CURRENT_VERSION" ]; then
        IS_UPGRADE=true
        echo "Upgrading from version $INSTALLED_VERSION to $CURRENT_VERSION"
      fi

      # Handle config files
      if [ "$IS_UPGRADE" = true ]; then
        # Backup entire config directory
        BACKUP_DIR="/backups/v$INSTALLED_VERSION"
        mkdir -p "$BACKUP_DIR"
        echo "Upgrading: Backing up to $BACKUP_DIR..."

        # Backup config files
        if [ -d "/app/config" ]; then
          cp -r /app/config "$BACKUP_DIR/"
          echo "  - Config files backed up"
        fi

        # Backup src files
        if [ -d "/app/src" ]; then
          cp -r /app/src "$BACKUP_DIR/"
          echo "  - Source files backed up"
        fi

        echo "Backup complete! Old files backed up at: $BACKUP_DIR"
      fi

      # initialize config and src if they do not exist
      cp -r /init/config/* /app/config/
      cp /init/src/index.js /app/src/

      if [ ! -d /app/src/admin ]; then
        cp -r /init/src/admin /app/src/
      fi

      # Initialize api folder only once (preserve all user-created and modified content types)
      if [ ! -d /app/src/api ]; then
        cp -r /init/src/api /app/src/
      fi

      if [ ! -d /app/src/components ] && [ -d /init/src/components ]; then
        cp -r /init/src/components /app/src/
      fi

      # Save current version
      echo "$CURRENT_VERSION" > "$VERSION_FILE"
    environment:
      - DATABASE_CLIENT=postgres
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
      - DATABASE_NAME=strapi
      - DATABASE_USERNAME=strapi
      - DATABASE_PASSWORD=strapi
      - DATABASE_SSL=false
      - JWT_SECRET=5a7d3c8e9f2b1a4c6d8e0f1a2b3c4d5e
      - ADMIN_JWT_SECRET=9f8e7d6c5b4a3d2c1e0f9a8b7c6d5e4f
      - APP_KEYS=app1key123456,app2key789012,app3keyabcdef,app4keyghijkl
      - API_TOKEN_SALT=a1b2c3d4e5f6g7h8i9j0
      - TRANSFER_TOKEN_SALT=z9y8x7w6v5u4t3s2r1q0
      - ENCRYPTION_KEY=e8f3a2b1c9d7e6f5a4b3c2d1e0f9a8b7c6d5e4f3a2b1c0
      - HOST=0.0.0.0
      - PORT=1337
      - NODE_ENV=development
      - __VITE_ADDITIONAL_SERVER_ALLOWED_HOSTS=strapi,localhost
    depends_on:
      - postgres
    binds:
      - /lzcapp/var/uploads:/app/public/uploads
      - /lzcapp/var/src:/app/src
      - /lzcapp/var/config:/app/config
      - /lzcapp/var/backups:/backups

  postgres:
    image: registry.lazycat.cloud/liu/library/postgres:120a228424c55ea8
    environment:
      - POSTGRES_DB=strapi
      - POSTGRES_USER=strapi
      - POSTGRES_PASSWORD=strapi
    binds:
      - /lzcapp/var/data:/var/lib/postgresql/data
    health_check:
      test:
        - CMD-SHELL
        - pg_isready -U strapi -d strapi
      start_period: 30s
