// Generated by AI, used to fix startup issues
// ┌──────────────────────────────────────────────────────────────────────────────┐
// │                                                                              │
// │   TypeError: Cannot read properties of undefined (reading 'map')             │
// │   at Object.register                                                         │
// │     (/app/node_modules/@strapi/content-type-builder/dist/server/register.js: │
// │     21:47)                                                                   │
// │   at Object.register                                                         │
// │     (/app/node_modules/@strapi/core/dist/domain/module/index.js:46:52)       │
// │   at Object.register                                                         │
// │     (/app/node_modules/@strapi/core/dist/registries/modules.js:30:27)        │
// │   at async Strapi.runPluginsLifecycles                                       │
// │     (/app/node_modules/@strapi/core/dist/Strapi.js:439:9)                    │
// │   at async Strapi.register                                                   │
// │     (/app/node_modules/@strapi/core/dist/Strapi.js:329:9)                    │
// │   at async Strapi.load                                                       │
// │     (/app/node_modules/@strapi/core/dist/Strapi.js:318:9)                    │
// │   at async Object.develop                                                    │
// │     (/app/node_modules/@strapi/strapi/dist/src/node/develop.js:170:32)       │
// │   at async action                                                            │
// │     (/app/node_modules/@strapi/strapi/dist/src/cli/commands/develop.js:15:9) │
// │   at async Command.parseAsync                                                │
// │     (/app/node_modules/commander/lib/command.js:923:5)                       │
// │   at async runCLI                                                            │
// │     (/app/node_modules/@strapi/strapi/dist/cli.js:89:5)                      │
// │                                                                              │
// └──────────────────────────────────────────────────────────────────────────────┘

module.exports = [
  'strapi::errors',
  'strapi::security',
  {
    name: 'strapi::session',
    config: {
      ownStore: true,
    },
  },
  'strapi::cors',
  'strapi::poweredBy',
  'strapi::logger',
  'strapi::query',
  'strapi::body',
  'strapi::favicon',
  'strapi::public',
];
